name: Push Docker Image to Nexus Repository

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t 5c27-103-108-207-58.ngrok-free.app:8081/jainish-docker/myimage:latest .

      - name: Save Docker image as tarball
        run: |
          docker save 5c27-103-108-207-58.ngrok-free.app:8081/jainish-docker/myimage:latest -o myapp.tar

      - name: Nexus Repository Publisher - Push Docker Image
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverurl:  https://5c27-103-108-207-58.ngrok-free.app:8081
          format: docker
          repository: jainish-docker
          coordinates: groupId=com.example artifactId=app version=1.0.0
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          assets: extension=tar
          filename: ./myapp.tar
