name: Build and Push Docker Images to GitLab Container Registry

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitLab Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }}

    # Build Image 1 with OCI Label
    - name: Build Image 1 with OCI LABEL
      run: |
        # Modify Dockerfile to include the OCI label
        echo "LABEL org.opencontainers.image.source=${{ github.repository }}" >> Dockerfile
        # Build and push the image with the label
        docker build --push --tag registry.gitlab.com/${{ secrets.GITLAB_USERNAME }}/gitlab-snyk/image-label:latest .

    # Build Image 2 with Attestation
    - name: Build Image 2 with Attestation
      run: |
        # Build and push the image with attestation using buildx
        docker buildx build --provenance=true --push --tag registry.gitlab.com/${{ secrets.GITLAB_USERNAME }}/gitlab-snyk/imageattestation:latest .
