name: Push Docker Image to Nexus Repository

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Nexus Docker registry
        uses: docker/login-action@v2
        with:
          registry: cf9d-103-108-207-58.ngrok-free.app
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      # Step 4: Build and push the Docker image with OCI label
      - name: Build and push Docker image with OCI label
        run: |
          docker build -t cf9d-103-108-207-58.ngrok-free.app/jainish-docker/label-image:latest --label org.opencontainers.image.source="https://github.com/jchauhan-crest/bitbucket-usercase-ui" --push .

      # Step 5: Build and push the Docker image with provenance
      - name: Build and push Image 2 with Provenance
        run: |
          docker buildx build --provenance=true -t cf9d-103-108-207-58.ngrok-free.app/jainish-docker/attestation-image:latest --push .