name: Push Docker Image to Nexus Repository

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Nexus Docker registry
        uses: docker/login-action@v2
        with:
          registry: cf9d-103-108-207-58.ngrok-free.app
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t cf9d-103-108-207-58.ngrok-free.app/jainish-docker/myimage:latest .

      - name: Push Docker image to Nexus
        run: |
          docker push cf9d-103-108-207-58.ngrok-free.app/jainish-docker/myimage:latest
