name: Push Docker Image to Nexus Repository

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      # Build and push image with OCI label
      # - name: Build and push Docker image with OCI label
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: registry.gitlab.com/sandip.bhesaniya/bitbucket_usecase/image-label:latest
      #     labels: |
      #       org.opencontainers.image.source=https://github.com/jchauhan-crest/bitbucket-usercase-ui

      # Build and push image with provenance
      - name: Build and push Image with Provenance
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: registry.gitlab.com/sandip.bhesaniya/bitbucket_usecase/image-attestation:latest
          provenance: true
